### ISSUE TITLE
Add it to tensorflow

### ISSUE THREAD

**Issue by Arsakes** [manelbaradad/munkres-tensorflow#1]
Hey man, great job I was looking exactly for something like this to solve my bbox - ground truth bbox matching problme in TF.

You should ask to add it in tensorflow contrib.

EDIT: Matching is bread & butter for object detection. However most people use many-to-one matching since really hard to implement one-to-one without modyfing code.

**Comment by mbaradad** [comment]
Thanks,
I think that this kind of operations are not supposed to be in core tf, as having lots of them would make tf even harder to maintain.
