### ISSUE TITLE
undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by beihangwenbin** [manelbaradad/munkres-tensorflow#7]
I can get hungarian.so by using the code  :
TF_INC=$(python -c 'import tensorflow as tf;print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I$TF_INC -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -O2
However when I load it ,the error  **tensorflow.python.framework.errors_impl.NotFoundError:undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv**  happens

**Comment by beihangwenbin** [comment]
I solve it by taking g++ version to 4.8 and tensorflow version to1.3 
and the code is  : 
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $TF_INC

**Comment by relh** [comment]
Tensorflow v1.4.1 should also work.
